import './globals.css';
import Head from 'next/head';
import Navbar from './components/Navbar/index';
import Footer from './components/Footer/index';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <title>Conservation Council Of Kashmir</title>
        <meta
          name="conservation council of kashmir"
          content="Generated by create next app"
        />
        {/* Add more head-related elements here */}
      </Head>
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
